### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by NunciosChums** [IanMitchell/slim-language#1]
Store package settings files in the `settings/` directory instead of `scoped-properties/`

```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:565:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:187:43)
```

**Comment by IanMitchell** [comment]
Thanks for the report! Struggled a bit with pushing an update, but think I got it :+1:

**Comment by NunciosChums** [comment]
Great job! Deprecate message dismissed! Thank you~
